=== aheadlabs/devops-toolset/src/devops_toolset/json-schemas/wordpress-constants-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://dev.aheadlabs.com/schemas/json/wordpress-constants-schema.json",
    "title": "WordPress site constants",
    "description": "WordPress site constants to generate and deploy a site automatically",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "defaults": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "version",
                "locale"
            ]
        },
        "paths": {
            "type": "object",
            "properties": {
                "devops": {
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "wordpress": {
                    "type": "string"
                },
                "content": {
                    "type": "object",
                    "properties": {
                        "themes": {
                            "type": "string"
                        },
                        "plugins": {
                            "type": "string"
                        },
                         "wxr": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "themes",
                        "plugins",
                        "wxr"
                    ]
                }
            },
            "additionalProperties": false,
            "additionalItems": false,
            "required": [
                "devops",
                "database",
                "wordpress",
                "content"
            ]
        },
        "packages": {
            "type": "object",
            "properties": {
                "devops_toolset": {
                    "type": "string",
                    "format": "uri-template"
                }
            }
        },
        "regex_base64": {
            "type": "array",
            "items": { "$ref": "http://dev.aheadlabs.com/schemas/json/keyvaluepair-schema.json" },
            "uniqueItems": true
        },
        "urls": {
            "type": "object",
            "properties": {
                "wp_theme_download": {
                    "type": "string",
                    "format": "uri"
                }
            },
            "required": ["wp_theme_download"]
        }
    },
    "additionalProperties": false,
    "required": [
        "defaults",
        "paths",
        "packages",
        "regex_base64",
        "urls"
    ]
}

=== aheadlabs/devops-toolset/devopstoolset/project_types/wordpress/wordpress-constants.json
{
    "$schema": "http://dev.aheadlabs.com/schemas/json/wordpress-constants-schema.json",
    "defaults": {
        "version":"latest",
        "locale":"en_US"        
    },
    "paths": {
        "devops":".devops",
        "database":"database",
        "wordpress":"wordpress",
        "content":{
            "themes":"content/themes",
            "plugins":"content/plugins",
            "wxr":"content/wxr"
        }
    },
    "packages": {
        "devops_toolset": "https://github.com/aheadlabs/devops-toolset/archive/master.zip",
        "wp_cli": "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    },
    "regex_base64": [
        {
            "key": "wordpress-theme",
            "value": "d29yZHByZXNzL3dwLWNvbnRlbnQvdGhlbWVzLyhbXHdcLV0rKS8="
        }
    ],
    "urls": {
        "wp_theme_download": "https://downloads.wordpress.org/theme/{slug}{version}.zip"
    }
}
